import type { User } from "./types";

export const mockUsers: User[] = [
  {
    id: "u-01",
    name: "Elena Vasquez",
    email: "elena.vasquez@glynac.ai",
    role: "Admin",
    status: "Active",
    lastActive: "2026-10-03T16:12:00Z",
    department: "Platform",
    avatarInitials: "EV",
    permissions: {
      vdr: ["Read", "Write", "Approve", "Admin"],
      chat: ["Read", "Write", "Approve", "Admin"],
      admin: ["Read", "Write", "Approve", "Admin"],
      tree: ["Read", "Write", "Approve", "Admin"],
    },
  },
  {
    id: "u-02",
    name: "Marcus Chen",
    email: "marcus.chen@glynac.ai",
    role: "Compliance Officer",
    status: "Active",
    lastActive: "2026-10-03T15:48:00Z",
    department: "Compliance",
    avatarInitials: "MC",
    permissions: {
      vdr: ["Read", "Write", "Approve"],
      chat: ["Read", "Write", "Approve"],
      admin: ["Read"],
      tree: ["Read", "Write"],
    },
  },
  {
    id: "u-03",
    name: "Priya Nair",
    email: "priya.nair@glynac.ai",
    role: "Advisor",
    status: "Active",
    lastActive: "2026-10-03T14:21:00Z",
    department: "Wealth Advisory",
    avatarInitials: "PN",
    permissions: {
      vdr: ["Read", "Write"],
      chat: ["Read", "Write"],
      admin: ["Read"],
      tree: ["Read"],
    },
  },
  {
    id: "u-04",
    name: "James Okafor",
    email: "james.okafor@glynac.ai",
    role: "Auditor",
    status: "Active",
    lastActive: "2026-10-02T19:04:00Z",
    department: "Internal Audit",
    avatarInitials: "JO",
    permissions: {
      vdr: ["Read"],
      chat: ["Read"],
      admin: ["Read"],
      tree: ["Read"],
    },
  },
  {
    id: "u-05",
    name: "Sofia Rossi",
    email: "sofia.rossi@glynac.ai",
    role: "Compliance Officer",
    status: "Pending",
    lastActive: "2026-09-28T11:10:00Z",
    department: "Compliance",
    avatarInitials: "SR",
    permissions: {
      vdr: ["Read"],
      chat: ["Read"],
      admin: [],
      tree: ["Read"],
    },
  },
  {
    id: "u-06",
    name: "Daniel Brooks",
    email: "daniel.brooks@glynac.ai",
    role: "Advisor",
    status: "Suspended",
    lastActive: "2026-09-12T08:33:00Z",
    department: "Private Banking",
    avatarInitials: "DB",
    permissions: {
      vdr: ["Read"],
      chat: ["Read"],
      admin: [],
      tree: [],
    },
  },
  {
    id: "u-07",
    name: "Amina Haddad",
    email: "amina.haddad@glynac.ai",
    role: "Compliance Officer",
    status: "Active",
    lastActive: "2026-10-03T09:02:00Z",
    department: "Surveillance",
    avatarInitials: "AH",
    permissions: {
      vdr: ["Read", "Write", "Approve"],
      chat: ["Read", "Write"],
      admin: ["Read"],
      tree: ["Read", "Write", "Approve"],
    },
  },
  {
    id: "u-08",
    name: "Noah Feldman",
    email: "noah.feldman@glynac.ai",
    role: "Advisor",
    status: "Active",
    lastActive: "2026-10-01T17:45:00Z",
    department: "Wealth Advisory",
    avatarInitials: "NF",
    permissions: {
      vdr: ["Read", "Write"],
      chat: ["Read", "Write"],
      admin: ["Read"],
      tree: ["Read"],
    },
  },
  {
    id: "u-09",
    name: "Hannah Park",
    email: "hannah.park@glynac.ai",
    role: "Admin",
    status: "Active",
    lastActive: "2026-10-03T16:40:00Z",
    department: "Security",
    avatarInitials: "HP",
    permissions: {
      vdr: ["Read", "Write", "Approve", "Admin"],
      chat: ["Read", "Write", "Approve", "Admin"],
      admin: ["Read", "Write", "Approve", "Admin"],
      tree: ["Read", "Write", "Approve"],
    },
  },
  {
    id: "u-10",
    name: "Luis Ortega",
    email: "luis.ortega@glynac.ai",
    role: "Auditor",
    status: "Pending",
    lastActive: "2026-09-30T13:18:00Z",
    department: "External Review",
    avatarInitials: "LO",
    permissions: {
      vdr: ["Read"],
      chat: ["Read"],
      admin: ["Read"],
      tree: ["Read"],
    },
  },
  {
    id: "u-11",
    name: "Claire Bennett",
    email: "claire.bennett@glynac.ai",
    role: "Advisor",
    status: "Active",
    lastActive: "2026-10-03T12:55:00Z",
    department: "Family Office",
    avatarInitials: "CB",
    permissions: {
      vdr: ["Read", "Write"],
      chat: ["Read", "Write"],
      admin: ["Read"],
      tree: ["Read"],
    },
  },
  {
    id: "u-12",
    name: "Kenji Watanabe",
    email: "kenji.watanabe@glynac.ai",
    role: "Compliance Officer",
    status: "Active",
    lastActive: "2026-10-02T22:07:00Z",
    department: "Policy",
    avatarInitials: "KW",
    permissions: {
      vdr: ["Read", "Write", "Approve"],
      chat: ["Read", "Write", "Approve"],
      admin: ["Read", "Write"],
      tree: ["Read", "Write"],
    },
  },
];
