import type { ActivityEvent } from "./types";

export const mockActivity: ActivityEvent[] = [
  {
    id: "a-01",
    user: "Marcus Chen",
    action: "Approved FINRA-2210 exception for account #4412",
    module: "Rules",
    timestamp: "2026-10-03T16:41:00Z",
    severity: "info",
  },
  {
    id: "a-02",
    user: "Priya Nair",
    action: "Uploaded Investment_Agreement_v4.pdf to VDR",
    module: "VDR",
    timestamp: "2026-10-03T16:28:00Z",
    severity: "info",
  },
  {
    id: "a-03",
    user: "System",
    action: "API latency exceeded 400ms on /reviews queue",
    module: "Health",
    timestamp: "2026-10-03T16:22:00Z",
    severity: "warning",
  },
  {
    id: "a-04",
    user: "Elena Vasquez",
    action: "Updated Hannah Park role permissions on Admin module",
    module: "RBAC",
    timestamp: "2026-10-03T16:11:00Z",
    severity: "info",
  },
  {
    id: "a-05",
    user: "Amina Haddad",
    action: "Flagged guaranteed-return language in marketing email",
    module: "Chat",
    timestamp: "2026-10-03T15:54:00Z",
    severity: "critical",
  },
  {
    id: "a-06",
    user: "Kenji Watanabe",
    action: "Toggled rule SUIT-04 to inactive",
    module: "Rules",
    timestamp: "2026-10-03T15:33:00Z",
    severity: "warning",
  },
  {
    id: "a-07",
    user: "Claire Bennett",
    action: "Asked AI assistant about Section 4.2 of IPS",
    module: "Chat",
    timestamp: "2026-10-03T15:12:00Z",
    severity: "info",
  },
  {
    id: "a-08",
    user: "Hannah Park",
    action: "Enabled Presidio PII Masking feature flag",
    module: "Flags",
    timestamp: "2026-10-03T14:48:00Z",
    severity: "info",
  },
  {
    id: "a-09",
    user: "System",
    action: "Database replica lag recovered (12ms)",
    module: "Health",
    timestamp: "2026-10-03T14:21:00Z",
    severity: "info",
  },
  {
    id: "a-10",
    user: "James Okafor",
    action: "Exported 90-day activity log for SEC exam package",
    module: "Admin",
    timestamp: "2026-10-03T13:05:00Z",
    severity: "info",
  },
  {
    id: "a-11",
    user: "Daniel Brooks",
    action: "Failed login from unrecognized device — account suspended",
    module: "RBAC",
    timestamp: "2026-10-02T08:14:00Z",
    severity: "critical",
  },
  {
    id: "a-12",
    user: "Noah Feldman",
    action: "Shared restricted folder with external auditor",
    module: "VDR",
    timestamp: "2026-10-02T18:40:00Z",
    severity: "warning",
  },
];

export const liveActivityPool: Omit<ActivityEvent, "id" | "timestamp">[] = [
  {
    user: "System",
    action: "Nightly archive job completed (14,208 objects)",
    module: "Health",
    severity: "info",
  },
  {
    user: "Marcus Chen",
    action: "Created custom rule CUST-18 for annuity illustrations",
    module: "Rules",
    severity: "info",
  },
  {
    user: "Priya Nair",
    action: "Regenerated AI citation for FINRA Rule 2210 §4",
    module: "Chat",
    severity: "info",
  },
  {
    user: "System",
    action: "Error rate on search indexer rose to 1.8%",
    module: "Health",
    severity: "warning",
  },
  {
    user: "Elena Vasquez",
    action: "Suspended pending user Sofia Rossi after incomplete KYC",
    module: "RBAC",
    severity: "warning",
  },
];
